apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  source:
    path: argocd/main-app/
    repoURL: "https://github.com/jilanisayyad/kube-tutorials"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
