apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: second-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jilanisayyad/kube-tutorials
    path: argocd/second-app/helm/
    helm:
      releaseName: second-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
