apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-argocd
  template:
    metadata:
      labels:
        app: app-argocd
    spec:
      containers:
        - name: name
          image: jilanigns3/web-server:blue
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 80
